alias ls="exa -a --icons --group-directories-first"
alias lt="exa -T -L=2 -a --icons --group-directories-first"
alias install="sudo dnf install"
alias remove="sudo dnf remove"
alias upgrade="sudo dnf upgrade"
alias stow="stow -t /home/igor"
alias n="n -dHi"