#!/bin/bash
paru -S \
    android-file-transfer \
    android-tools \
    anydesk-bin \
    bat \
    bc \
    bibata-cursor-theme \
    blueman \
    bluez-utils \
    brillo \
    btop \
    c-lolcat \
    cliphist \
    dashbinsh \
    ddcci-driver-linux-dkms \
    ddcutil \
    dkms \
    docker \
    docker-compose \
    downgrade \
    dragon-drop \
    dunst \
    easyeffects \
    exa \
    exfatprogs \
    fd \
    ffmpeg \
    figlet-fonts-extra \
    firefox \
    flatpak \
    fnm \
    font-manager \
    fzf \
    gammastep \
    gdu \
    gimp-devel \
    github-cli \
    glow \
    gnome-keyring \
    gparted \
    greetd-tuigreet \
    grim \
    gvfs \
    helvum \
    hyprpaper \
    hyprpicker \
    imagemagick \
    inkscape \
    jq \
    kitty \
    kvantum \
    lavat-git \
    lazydocker \
    lazygit \
    ledger-live-bin \
    lf \
    libreoffice-fresh \
    linux-headers \
    losslesscut-bin \
    man-db \
    mpv \
    mtpfs \
    mumble \
    nasc \
    ncspot-bin \
    nfs-utils \
    nvtop \
    nwg-look \
    obs-studio \
    obsidian \
    ocrmypdf \
    pacman-contrib \
    papirus-folders-git \
    papirus-icon-theme \
    pavucontrol \
    pfetch-rs-bin \
    polkit-gnome \
    procs \
    pulsemixer \
    python-beautifulsoup4 \
    python-dotenv \
    python-numpy \
    python-pillow \
    python-pip \
    python-pipreqs \
    python-pipx \
    python-pynvim \
    python-pytelegrambotapi \
    python-requests \
    python-rich \
    python-setuptools \
    python-tabulate \
    python-undetected-chromedriver \
    python-wxpython \
    qt5-imageformats \
    qt5-wayland \
    qt5ct \
    qt6-wayland \
    qt6ct \
    quickgui-bin \
    qview \
    ripgrep \
    rofi-calc \
    rofi-emoji \
    rofi-lbonn-wayland-git \
    rofi-rbw \
    shell-gpt \
    slurp \
    solaar \
    speedtest-rs-bin \
    spotify-edge \
    telegram-desktop \
    thorium-browser-bin \
    thunar \
    thunar-archive-plugin \
    thunar-volman \
    tldr \
    transmission-gtk \
    unzip \
    upscayl-bin \
    ventoy-bin \
    vial-appimage \
    visual-studio-code-bin \
    waybar \
    wget \
    wireguard-tools \
    wl-clipboard \
    wl-screenrec-git \
    wtype \
    xdg-desktop-portal-hyprland \
    xdg-ninja \
    xorg-xhost \
    yt-dlp \
    zip \
    zoxide \
    zsh-autosuggestions \
    zsh-history-substring-search \
    zsh-syntax-highlighting \
    zsh-theme-powerlevel10k-git
