#!/usr/bin/env dash

workspace_id=$(hyprctl -j activeworkspace | jq -r '.id')

hyprctl -j clients |
	jq \
		--argjson id "$workspace_id" \
		-r '.[] 
        | select(.workspace.id == $id) 
        | "\(.at[0] + 1),\(.at[1] + 1) \(.size[0] - 1)x\(.size[1] - 1)"' |
	slurp \
		-r \
		-w 0 \
		-b '#00000000' \
		-B '#00000000' \
		-s '#ffffff4d'
