#!/usr/bin/env dash

if [ "$#" -lt 2 ]; then
	echo "Usage: wally <input> <output>"
	exit 1
fi

mask=~/Pictures/wallpapers/mask_vertical_4k.avif
input="$1"
output="$2"
resolution="3840x2160"

magick "$input" -resize "${resolution}^" \
	-gravity center -extent "$resolution" \
	-quality 100 +repage "$output"

magick "$output" "$mask" \
	-compose Over -composite \
	-quality 100 "$output"
