alias ls="exa -a --icons --group-directories-first -s ext"
alias lt="exa -T -L=2 -a --icons --group-directories-first"
alias stow="stow --no-folding -t /home/igor"
alias n="n -dHi"
alias archive="tar -caf"
alias untar="tar -xaf"
alias mkdir="mkdir -p"
alias rm="trash"
alias cat="bat -p"