alias ls="exa -a --icons --group-directories-first -s ext"
alias lt="exa -T -L=2 -a --icons --group-directories-first"
alias install="sudo dnf install"
alias remove="sudo dnf remove"
alias up="sudo dnf upgrade"
alias autoremove="sudo dnf autoremove"
alias repos="dnf repolist"
alias stow="stow --no-folding -t /home/igor"
alias n="n -dHi"
alias archive="tar -caf"
alias untar="tar -xaf"
alias mkdir="mkdir -p"
alias colors="curl -s https://gist.githubusercontent.com/HaleTom/89ffe32783f89f403bba96bd7bcd1263/raw/e50a28ec54188d2413518788de6c6367ffcea4f7/print256colours.sh | bash"
alias nsxiv="nsxiv -a ."
alias rm="trash"